version: '2'
services:
    nodejs:
        container_name: zpw-nodejs
        build: ./docker
        image: mfrankiewicz/zpw-nodejs
        volumes:
            - ./app:/usr/src/app
        ports:
            - "80:80"
